name: new Release
on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Build and Push Container Image
        uses: docker/build-push-action@v1
        with:
          dockerfile: Dockerfile
          registry: ${{ vars.REGISTRY_LOGIN_SERVER }}
          repository: ${{ github.event.repository.name }}
          username: ${{ vars.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          tag_with_ref: true
          tag_with_sha: true

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Add TAG_NAME env property
        run:  echo "TAG_NAME=`echo ${GITHUB_REF#refs/tags/}`" >> $GITHUB_ENV
      - name: Open PR in Environment Repository for new App Version
        env:
          ENV_REPO: ${{ github.event.repository.owner.name }}/gitops-example-environment
        uses: benc-uk/workflow-dispatch@v1.1
        with:
          workflow: New Application Version
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          inputs: '{"tag_name": "${{ env.TAG_NAME }}", "app_repo": "${{ github.event.repository.name }}", "image": "${{ vars.REGISTRY_LOGIN_SERVER }}/${{ github.event.repository.name }}:${{ env.TAG_NAME }}"}'
          ref: refs/heads/main
          repo: ${{ env.ENV_REPO }}
